import Navbar from "./Navbar";
import Hero from './Hero';
import Security from "./Security";
import SavingWays from "./SavingWays";
import Investify from "./Investify";
import Saver from "./Saver";
import Testimonial from "./Testimonial";
import Featured from "./Featured";
import Footer from "./Footer";
export {Navbar, Hero, Security, SavingWays, Investify, Saver, Testimonial, Featured, Footer};